# test-serverless -> serverless.yml

service: test-service

#plugins:
#  - serverless-offline

#custom:
#  serverless-offline:
#    httpsProtocol: "dev-certs"
#    port: 8080

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    NODE_PATH: "./:/opt/node_modules"

package:
  exclude:
    - dev-certs/**
    - .vscode/**
    - node_modules/**
    - .gitignore
    - notes.md
    - package.json
    - package-lock.json

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
      - http:
          path: test
          method: get
      - http:
          path: test/{id}
          method: get
